### ISSUE TITLE
Proxyfile support

### ISSUE THREAD

**Issue by 3xtazzy** [f4rber/Dorker#1]
Don’t you think it’s nicer to have proxy support? (Socks5 would be appreciates or every proxy type)

i’m afraid my IP got banned because too much dork and pages in a short time.

**Comment by ghost** [comment]
Thats what proxychains are for sir !! No need for him to edit the script

**Comment by 3xtazzy** [comment]
> Thats what proxychains are for sir !! No need for him to edit the script

Great! I don't know about that tool. Thanks :D

**Comment by f4rber** [comment]
Added http proxy support, you need to create a "proxy_list.txt" which will contain proxies like:
192.167.81.18:8080
128.171.81.18:80
34.63.31.168:5427

**Comment by 3xtazzy** [comment]
> Added http proxy support, you need to create a "proxy_list.txt" which will contain proxies like:
> 192.167.81.18:8080
> 128.171.81.18:80
> 34.63.31.168:5427

Thanks, but socks is not working?

**Comment by f4rber** [comment]
Maybe in next update i will add socks support
